# script name must be "app_handle_name.app.rb"
app_handle_name = "sample_lua_app"
app_screen_name = "lua app"
#default_window_mode = "background" # or "fullwindow" or "window" or "background"
default_window_mode = "window" # or "fullwindow" or "window" or "background"

# if fullscreen/fullwindow, they will be ignored
default_window_width = 150
default_window_height = 150

# if fullscreen/fullwindow, they will be ignored
default_window_pos_x = 300
default_window_pos_y = 115
