app_handle_name = "sample_mruby_app"
app_screen_name = "Sample mruby Application"
default_window_mode = "fullscreen" # or "fullwindow" or "window" or "background"

# if fullscreen/fullwindow, they will be ignored
default_window_width = 0
default_window_height = 0

# if fullscreen/fullwindow, they will be ignored
default_window_pos_x = 0 
default_window_pos_y = 0
